version: '2'
services:
  contacts-postgresql:
    image: postgres:12.3
    volumes:
      - ~/volumes/jhipster/contacts/postgresql/:/var/lib/contacts/data/
    environment:
      - POSTGRES_USER=${PG_DATABASE_DEV_USER}
      - POSTGRES_PASSWORD=${PG_DATABASE_DEV_PASSWORD}
      - POSTGRES_DB=contacts
    ports:
      - 21001:5432
